name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  # LW METRICS ACHIEVEMENTS
  metrics-achievements:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.LW_METRICS }}
          filename: ${{ github.job }}.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
  # LW METRICS LANGUAGES
  metrics-languages:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.LW_METRICS }}
          filename: ${{ github.job }}.svg
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 500
          plugin_languages_ignored: dockerfile, makefile
